version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      # Following line is needed for Kafka versions 0.11+
      # in case you run less than 3 Kafka brokers in your
      # cluster because the broker config
      # `offsets.topic.replication.factor` (default: 3)
      # is now enforced upon topic creation
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  jupyter:
    image: jupyter/all-spark-notebook
    container_name: jupyter
    ports:
      - "8889:8888"
      - "4040:4040"
      - "4041:4041"
    expose:
      - "9999"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./dataset:/home/jovyan/dataset
      - ./spark:/home/jovyan/spark
    links:
      - master
      
  
  python3:
    image: orozcohsu/alpine-py3-pandas-nltk
    container_name: python3
    stdin_open: true
    tty: true
    volumes:
      - ./python:/root/python 
      - exchange-hdfs:/root/exchange-hdfs

  master:
    image: orozcohsu/ha-sp-ze-zo-hi-fl:v7
    container_name: master
    hostname: master
    environment:
      - "NODE_TYPE=master"
    expose:
      - "50070"
      - "9000"
    ports:
      - "8088:8088"
      - "50070:50070"
      - "9000:9000"
      - "2222:22"
      - "8080:8080"
      - "18080:18080"
      - "10000:10000"
      - "10002:10002"
      - "9083:9083"
    volumes:
      - /tmp/docker-cluster-hadoop-name/:/data/dfs/name/
      - /tmp/docker-cluster-hadoop-data/:/data/dfs/data/
      - /tmp/docker-cluster-hadoop-logs/:/usr/local/hadoop/logs/
      - /tmp/docker-cluster-zookeeper-logs/:/var/log/zookeeper/
      - /tmp/docker-cluster-zeppelin-logs/:/usr/local/zeppelin/log
      - ./mapreduce:/root/mapreduce
  slave1:
    image: lewuathe/hadoop-slave
    container_name: slave1
    depends_on:
      - master
    ports:
      - "9901:9864"
      - "8041:8042"
  slave2:
    image: lewuathe/hadoop-slave
    container_name: slave2
    depends_on:
      - master
    ports:
      - "9902:9864"
      - "8042:8042"


volumes:
  es7data1:
    driver: local
  es7data2:
    driver: local
  exchange-hdfs:
  
networks:
  es7net:
